export const content = `
<h2>1. Introduction</h2>

<p>
  Kalman filters have been a staple of engineering control systems since the 1960s, but their application
  to financial time series remains relatively niche compared to moving averages, GARCH models, or machine
  learning approaches. The appeal of Kalman filtering for finance lies in its recursive, Bayesian framework:
  rather than estimating a static model from a fixed window of data, the Kalman filter continuously updates
  its state estimate as each new observation arrives, weighting new information against prior beliefs through
  an optimal gain parameter. This makes it naturally adaptive to changing market conditions without the
  arbitrary window-length choices that plague traditional technical indicators.
</p>

<p>
  The challenge with Kalman filtering in finance is that the state-space model must be specified <em>a priori</em>.
  For a gold price series, what is the "state" being estimated? The most natural choice is the drift rate
  &mdash; the instantaneous expected return. If we model gold's minute-by-minute returns as a random walk
  with time-varying drift, the Kalman filter extracts a smoothed estimate of that drift, filtering out
  observation noise to reveal the underlying trend. When the filtered drift diverges from the observed price,
  a mean-reversion opportunity may exist.
</p>

<p>
  A separate but complementary question is whether the market operates in distinct regimes. A Hidden Markov
  Model (HMM) formalises this intuition: the observed returns are generated by one of $K$ latent states
  (e.g., "trending" and "mean-reverting"), each with its own return distribution. The HMM estimates which
  state is active at each point in time, enabling regime-conditional trading strategies. Combining Kalman
  filtering with HMM regime detection offers a principled framework: use the Kalman filter for signal
  generation and the HMM for signal filtration &mdash; only trading mean-reversion signals when the HMM
  indicates a mean-reverting regime.
</p>

<p>
  This paper implements and tests both approaches on XAUUSD M1 data, using a systematic grid search over
  stop-loss and take-profit parameters, with realistic spread costs and cooldown constraints.
</p>

<div style="background: #fffbeb; border: 1px solid #f59e0b; border-radius: 0.5rem; padding: 1rem 1.25rem; margin: 1.5rem 0;">
  <strong style="color: #b45309;">Simulated Results Disclaimer:</strong> All performance figures in this paper
  are derived from historical backtests on simulated or replayed market data with modelled transaction costs.
  They do not represent live trading results and should not be interpreted as indicative of future performance.
  A fixed spread cost of $0.20 per round-trip is applied throughout.
</div>

<h2>2. Kalman Drift Filter</h2>

<h3>2.1 State-Space Formulation</h3>

<p>
  We model XAUUSD M1 log returns as a noisy observation of a latent drift process. The state-space model is:
</p>

<p><strong>State equation</strong> (drift evolution):</p>

$$\\mu_t = \\mu_{t-1} + \\eta_t, \\quad \\eta_t \\sim \\mathcal{N}(0, Q)$$

<p><strong>Observation equation</strong> (return generation):</p>

$$r_t = \\mu_t + \\varepsilon_t, \\quad \\varepsilon_t \\sim \\mathcal{N}(0, R)$$

<p>
  where $\\mu_t$ is the latent drift at bar $t$, $r_t$ is the observed log return, $Q$ is the process
  noise variance (how much the drift can change per bar), and $R$ is the observation noise variance
  (how noisy individual returns are relative to the true drift). The ratio $Q/R$ controls the
  filter's responsiveness: high $Q/R$ makes the filter track observations closely (like a short
  moving average); low $Q/R$ produces heavy smoothing (like a long moving average).
</p>

<h3>2.2 Kalman Recursion</h3>

<p>
  The filter operates recursively through three steps at each bar $t$:
</p>

<p><strong>Prediction step:</strong></p>

$$\\hat{\\mu}_{t|t-1} = \\hat{\\mu}_{t-1}$$
$$P_{t|t-1} = P_{t-1} + Q$$

<p><strong>Update step:</strong></p>

$$K_t = \\frac{P_{t|t-1}}{P_{t|t-1} + R}$$
$$\\hat{\\mu}_t = \\hat{\\mu}_{t|t-1} + K_t(r_t - \\hat{\\mu}_{t|t-1})$$
$$P_t = (1 - K_t)P_{t|t-1}$$

<p>
  where $K_t$ is the Kalman gain &mdash; the fraction of the "surprise" ($r_t - \\hat{\\mu}_{t|t-1}$)
  that is incorporated into the new drift estimate. The gain converges to a steady-state value
  $K^* = \\frac{-R + \\sqrt{R^2 + 4QR}}{2R}$ after a burn-in period, at which point the filter
  behaves as an exponentially weighted moving average of returns with a decay rate determined by
  $Q$ and $R$.
</p>

<h3>2.3 Parameter Selection</h3>

<p>
  We set $Q = 10^{-8}$ and $R = 10^{-5}$, giving a ratio $Q/R = 10^{-3}$. This produces a
  heavily smoothed drift estimate that changes slowly &mdash; the filter assigns 99.9% of each
  return's variance to observation noise rather than genuine drift changes. The resulting
  steady-state Kalman gain is approximately $K^* \\approx 0.0316$, meaning only 3.16% of each
  bar's "surprise" return is incorporated into the drift estimate.
</p>

<p>
  This parameterisation is deliberate: at the M1 frequency, gold returns are dominated by
  microstructure noise (bid-ask bounce, order flow imbalances, tick clustering). A high $Q/R$
  ratio would cause the filter to chase every tick, producing a noisy drift estimate that is
  useless for mean-reversion. The low $Q/R$ ratio extracts only the slow-moving component of
  drift, which represents the genuine directional trend at the multi-hour scale.
</p>

<div style="margin: 2rem 0;">
  <img src="/charts/kalman/kalman_drift_gold_24h.png" alt="Kalman drift filter applied to 24 hours of XAUUSD M1 data" style="width: 100%; border-radius: 0.5rem; border: 1px solid #e5e7eb;" />
  <p class="figure-caption">Figure 1: Kalman drift filter applied to 24 hours of XAUUSD M1 data. The top panel shows the close price and Kalman-filtered price (cumulative sum of filtered drift); the bottom panel shows the raw M1 returns and the Kalman drift estimate. The filter smooths through microstructure noise to reveal the underlying trend direction.</p>
</div>

<h3>2.4 Filtered Price Construction</h3>

<p>
  From the drift sequence $\\{\\hat{\\mu}_t\\}$, we construct a filtered price series by cumulative
  summation of the drift estimates:
</p>

$$\\hat{P}_t = P_0 \\cdot \\exp\\left(\\sum_{s=1}^{t} \\hat{\\mu}_s\\right)$$

<p>
  The deviation between the observed price $P_t$ and the filtered price $\\hat{P}_t$ provides the
  basis for mean-reversion signals. When the observed price is above the filtered price, gold has
  "overshot" relative to the Kalman-estimated trend; when below, it has "undershot." The magnitude
  of this deviation, normalised by a rolling estimate of typical deviation, generates the trading signal.
</p>

<h2>3. Mean-Reversion Strategy</h2>

<h3>3.1 Signal Generation</h3>

<p>
  The mean-reversion signal is based on the distance between the observed price and the Kalman-filtered
  price, normalised by the rolling 1-hour (60-bar) mean absolute distance:
</p>

$$d_t = P_t - \\hat{P}_t$$
$$\\bar{d}_{60} = \\frac{1}{60}\\sum_{s=t-59}^{t} |d_s|$$
$$\\text{signal}_t = \\frac{d_t}{\\bar{d}_{60}}$$

<p>
  <strong>Entry rules:</strong>
</p>

<ul>
  <li><strong>Short entry:</strong> When $\\text{signal}_t > K_{\\text{thresh}}$ (price is above filtered
    price by more than $K_{\\text{thresh}}$ times the rolling mean distance), enter a short position
    expecting reversion toward the filtered price.</li>
  <li><strong>Long entry:</strong> When $\\text{signal}_t < -K_{\\text{thresh}}$, enter a long position.</li>
</ul>

<p>
  We use $K_{\\text{thresh}} = 0.05$ as the entry threshold. This is a relatively sensitive trigger,
  designed to capture the majority of reversion opportunities rather than waiting for extreme deviations.
</p>

<p>
  <strong>Exit rules:</strong> Each trade is managed with a fixed stop-loss (SL) and take-profit (TP).
  We grid-search over SL $\\in \\{1, 2, 3, 5\\}$ dollars and TP $\\in \\{0, 1, 2, 3, 5\\}$ dollars,
  where TP = 0 means "exit only on signal reversal or stop-loss." A minimum cooldown of 5 bars
  between consecutive trades prevents signal clustering from generating excessive transaction costs.
</p>

<p>
  <strong>Spread cost:</strong> A fixed spread of $0.20 per round-trip is applied to all trades.
  This represents a conservative estimate for XAUUSD during liquid hours (London/NY overlap), though
  spreads can widen to $0.50+ during Asian session lows.
</p>

<div style="margin: 2rem 0;">
  <img src="/charts/kalman/kalman_reversion_backtest.png" alt="Kalman mean-reversion strategy backtest results" style="width: 100%; border-radius: 0.5rem; border: 1px solid #e5e7eb;" />
  <p class="figure-caption">Figure 2: Kalman mean-reversion strategy backtest equity curves for the top parameter configurations. The equity curves show the cumulative P&L (after $0.20 spread) across the full test period. Different SL/TP combinations produce varying risk/return profiles, but all profitable configurations share the characteristic of tight stops relative to take-profits.</p>
</div>

<h3>3.2 Grid Search Results</h3>

<p>
  The grid search over 20 SL/TP combinations produces 647 trades across the test period. The results
  are summarised below for the top configurations:
</p>

<table>
  <tr>
    <th>SL ($)</th>
    <th>TP ($)</th>
    <th>Trades</th>
    <th>Win Rate</th>
    <th>Profit Factor</th>
    <th>Avg Trade ($)</th>
    <th>Max DD ($)</th>
    <th>Sharpe (ann.)</th>
  </tr>
  <tr>
    <td>2</td>
    <td>3</td>
    <td>647</td>
    <td>53.8%</td>
    <td>1.34</td>
    <td>+0.41</td>
    <td>&minus;28.4</td>
    <td>0.92</td>
  </tr>
  <tr>
    <td>2</td>
    <td>2</td>
    <td>647</td>
    <td>56.1%</td>
    <td>1.27</td>
    <td>+0.28</td>
    <td>&minus;22.7</td>
    <td>0.84</td>
  </tr>
  <tr>
    <td>3</td>
    <td>5</td>
    <td>647</td>
    <td>49.3%</td>
    <td>1.21</td>
    <td>+0.33</td>
    <td>&minus;41.2</td>
    <td>0.71</td>
  </tr>
  <tr>
    <td>1</td>
    <td>2</td>
    <td>647</td>
    <td>48.5%</td>
    <td>1.18</td>
    <td>+0.19</td>
    <td>&minus;18.9</td>
    <td>0.68</td>
  </tr>
  <tr>
    <td>5</td>
    <td>5</td>
    <td>647</td>
    <td>53.2%</td>
    <td>1.12</td>
    <td>+0.24</td>
    <td>&minus;52.6</td>
    <td>0.53</td>
  </tr>
  <tr>
    <td>1</td>
    <td>1</td>
    <td>647</td>
    <td>52.4%</td>
    <td>1.05</td>
    <td>+0.05</td>
    <td>&minus;16.3</td>
    <td>0.22</td>
  </tr>
</table>

<p>
  The best configuration uses SL = $2, TP = $3, achieving a profit factor of 1.34 with a 53.8%
  win rate across 647 trades. The asymmetric SL/TP ratio (1:1.5) is characteristic of mean-reversion
  strategies, where the edge comes from the tendency of deviations to revert, but the risk comes
  from regime changes where the deviation becomes permanent (trend continuation).
</p>

<p>
  Notably, very tight stops (SL = $1) produce lower win rates despite limiting losses per trade.
  This is because M1 gold prices exhibit sufficient intrabar volatility to trigger $1 stops on
  noise alone, before the reversion has time to materialise. The SL = $2 threshold provides
  enough room for the typical noise amplitude while still limiting downside in genuine trend moves.
</p>

<h2>4. HMM Regime Overlay</h2>

<h3>4.1 Hidden Markov Model Specification</h3>

<p>
  We fit a 2-state Gaussian HMM to the XAUUSD M1 return series. The two states are interpreted as:
</p>

<ul>
  <li><strong>State 0 (Mean-Reverting):</strong> Low-volatility regime with returns clustering near zero.
    In this state, deviations from the Kalman-filtered price are more likely to revert because the
    underlying drift is stable.</li>
  <li><strong>State 1 (Trending):</strong> High-volatility regime with larger absolute returns and
    potential for sustained directional moves. In this state, deviations from the filtered price may
    represent genuine trend changes rather than temporary overshoots.</li>
</ul>

<p>
  The HMM is parameterised by:
</p>

<ul>
  <li><strong>Emission distributions:</strong> $r_t | s_t = k \\sim \\mathcal{N}(\\mu_k, \\sigma_k^2)$
    for $k \\in \\{0, 1\\}$</li>
  <li><strong>Transition matrix:</strong> $A_{ij} = P(s_t = j | s_{t-1} = i)$, a $2 \\times 2$ matrix
    governing regime persistence and switching probabilities</li>
  <li><strong>Initial distribution:</strong> $\\pi_k = P(s_0 = k)$</li>
</ul>

<p>
  Parameters are estimated via the Baum-Welch algorithm (EM for HMMs) on a rolling training window.
  The Viterbi algorithm then provides the most likely state sequence $\\{\\hat{s}_t\\}$, which is used
  as the regime classification for trading decisions.
</p>

<div style="margin: 2rem 0;">
  <img src="/charts/kalman/hmm_regime_explorer.png" alt="HMM regime classification on XAUUSD M1 data" style="width: 100%; border-radius: 0.5rem; border: 1px solid #e5e7eb;" />
  <p class="figure-caption">Figure 3: HMM regime classification applied to XAUUSD M1 data. The top panel shows the price series colour-coded by regime (blue = mean-reverting, red = trending). The bottom panel shows the posterior probability of the mean-reverting state over time. Regime transitions are sharp, with most posterior probabilities near 0 or 1, indicating clear regime separation.</p>
</div>

<h3>4.2 Regime Characteristics</h3>

<p>
  The fitted HMM reveals two well-separated states with distinct statistical properties:
</p>

<table>
  <tr>
    <th>Property</th>
    <th>State 0 (Mean-Reverting)</th>
    <th>State 1 (Trending)</th>
  </tr>
  <tr>
    <td>Mean return ($\\mu_k$)</td>
    <td>$\\approx 0$</td>
    <td>Variable (positive or negative)</td>
  </tr>
  <tr>
    <td>Volatility ($\\sigma_k$)</td>
    <td>Low (0.5&ndash;1.0x avg)</td>
    <td>High (1.5&ndash;3.0x avg)</td>
  </tr>
  <tr>
    <td>Self-transition prob ($A_{kk}$)</td>
    <td>0.985&ndash;0.995</td>
    <td>0.970&ndash;0.990</td>
  </tr>
  <tr>
    <td>Expected sojourn time</td>
    <td>67&ndash;200 bars (1&ndash;3 hours)</td>
    <td>33&ndash;100 bars (30 min&ndash;2 hours)</td>
  </tr>
  <tr>
    <td>Fraction of time</td>
    <td>~65%</td>
    <td>~35%</td>
  </tr>
</table>

<p>
  The mean-reverting state dominates (approximately 65% of bars), consistent with the well-documented
  tendency of gold to oscillate within ranges during quiet market hours (Asian session, pre-London).
  The trending state captures news-driven moves, session opens, and sustained directional flows.
  The high self-transition probabilities (0.97&ndash;0.99) indicate strong regime persistence: once
  gold enters a regime, it tends to stay there for tens of minutes to hours before switching.
</p>

<div style="margin: 2rem 0;">
  <img src="/charts/kalman/hmm_sojourn_distributions.png" alt="HMM sojourn time distributions" style="width: 100%; border-radius: 0.5rem; border: 1px solid #e5e7eb;" />
  <p class="figure-caption">Figure 4: Sojourn time distributions for the two HMM states. The mean-reverting state (left) has a longer average duration (67&ndash;200 bars) with a heavy right tail, while the trending state (right) is shorter-lived (33&ndash;100 bars). Both distributions are approximately geometric, consistent with the Markov assumption.</p>
</div>

<h3>4.3 Filtered Trading Strategy</h3>

<p>
  The HMM-filtered strategy applies a simple rule: <strong>only enter mean-reversion trades when the
  HMM indicates State 0 (mean-reverting)</strong>. Signals generated during State 1 (trending) are
  suppressed entirely. The logic is straightforward &mdash; mean-reversion signals during trending
  regimes are likely to be counter-trend entries that will be stopped out as the trend continues.
</p>

<p>
  All other parameters (Kalman filter settings, SL/TP grid, cooldown, spread cost) remain identical
  to the unfiltered strategy, allowing a clean comparison of the HMM overlay's contribution.
</p>

<h2>5. Results</h2>

<h3>5.1 Kalman-Only vs Kalman+HMM Comparison</h3>

<p>
  We compare the best Kalman-only configuration (SL = $2, TP = $3) against the same configuration
  with HMM filtering applied. The HMM filter reduces the total number of trades by suppressing
  signals during trending regimes.
</p>

<table>
  <tr>
    <th>Metric</th>
    <th>Kalman Only</th>
    <th>Kalman + HMM</th>
    <th>Change</th>
  </tr>
  <tr>
    <td>Total Trades</td>
    <td>647</td>
    <td>421</td>
    <td>&minus;35%</td>
  </tr>
  <tr>
    <td>Win Rate</td>
    <td>53.8%</td>
    <td>55.6%</td>
    <td>+1.8pp</td>
  </tr>
  <tr>
    <td>Profit Factor</td>
    <td>1.34</td>
    <td>1.42</td>
    <td>+0.08</td>
  </tr>
  <tr>
    <td>Avg Trade ($)</td>
    <td>+0.41</td>
    <td>+0.53</td>
    <td>+$0.12</td>
  </tr>
  <tr>
    <td>Cumulative PnL ($)</td>
    <td>+265</td>
    <td>+223</td>
    <td>&minus;$42</td>
  </tr>
  <tr>
    <td>Max Drawdown ($)</td>
    <td>&minus;28.4</td>
    <td>&minus;21.7</td>
    <td>+$6.7</td>
  </tr>
  <tr>
    <td>Sharpe (ann.)</td>
    <td>0.92</td>
    <td>1.08</td>
    <td>+0.16</td>
  </tr>
  <tr>
    <td>Calmar Ratio</td>
    <td>9.33</td>
    <td>10.28</td>
    <td>+0.95</td>
  </tr>
</table>

<div style="margin: 2rem 0;">
  <img src="/charts/kalman/kalman_hmm_backtest.png" alt="Kalman-only vs Kalman+HMM equity curves" style="width: 100%; border-radius: 0.5rem; border: 1px solid #e5e7eb;" />
  <p class="figure-caption">Figure 5: Equity curve comparison between Kalman-only (blue) and Kalman+HMM (orange) strategies. The HMM-filtered strategy has fewer drawdowns but also lower total P&L due to the reduced trade count. The smoother curve reflects the removal of losing counter-trend trades during trending regimes.</p>
</div>

<div class="finding-box">
  <strong>Key Finding:</strong> The HMM filter improves per-trade quality metrics (win rate +1.8pp,
  profit factor 1.34 &rarr; 1.42, Sharpe 0.92 &rarr; 1.08) but reduces total P&L by 16% due to
  the 35% reduction in trade count. The HMM acts as a precision filter &mdash; it removes the
  worst trades but also removes some winning trades that happen to occur near regime boundaries.
</div>

<h3>5.2 What the HMM Removes</h3>

<p>
  Of the 226 trades suppressed by the HMM filter, we can examine their hypothetical outcomes to
  understand what the filter is doing:
</p>

<ul>
  <li><strong>Suppressed losing trades:</strong> 119 of the 226 suppressed trades (52.7%) would have
    been losers. This is slightly better than the overall losing rate (46.2%), confirming that the
    HMM preferentially removes low-quality signals.</li>
  <li><strong>Suppressed winning trades:</strong> 107 of the 226 suppressed trades (47.3%) would have
    been winners. This is the cost of regime filtering &mdash; some genuine mean-reversion signals
    occur during what the HMM classifies as trending regimes, particularly at regime transition
    points where the HMM is uncertain.</li>
  <li><strong>Net effect of suppressed trades:</strong> The 226 suppressed trades have an average
    P&L of +$0.19, lower than the overall average (+$0.41) but still positive. The HMM removes
    the lower-quality half of trades, but since even the lower-quality trades have a slight positive
    expectancy, the total P&L decreases.</li>
</ul>

<h3>5.3 HMM Transition Behaviour</h3>

<div style="margin: 2rem 0;">
  <img src="/charts/kalman/hmm_transition_backtest.png" alt="Trade outcomes near HMM regime transitions" style="width: 100%; border-radius: 0.5rem; border: 1px solid #e5e7eb;" />
  <p class="figure-caption">Figure 6: Trade outcomes stratified by proximity to HMM regime transitions. Trades entered during stable MR regimes (far from transitions) have the highest win rate and profit factor, while trades near transition boundaries show degraded performance, regardless of whether the HMM classifies the regime as MR or trending.</p>
</div>

<p>
  The most informative analysis stratifies trade outcomes by their proximity to regime transitions.
  Trades entered during "stable" mean-reverting regimes (more than 30 bars from any transition)
  show a win rate of 58.2% and profit factor of 1.61. Trades entered within 10 bars of a transition
  show a win rate of 49.1% and profit factor of 0.96 &mdash; essentially no edge. This suggests
  that the HMM's primary value is identifying <em>stable</em> mean-reverting periods, not merely
  classifying the current regime.
</p>

<h3>5.4 Dual Strategy Analysis</h3>

<div style="margin: 2rem 0;">
  <img src="/charts/kalman/kalman_dual_backtest.png" alt="Kalman dual strategy backtest" style="width: 100%; border-radius: 0.5rem; border: 1px solid #e5e7eb;" />
  <p class="figure-caption">Figure 7: Dual strategy backtest showing the performance of mean-reversion (MR state) and trend-following (Trend state) strategies running simultaneously. The MR component generates the majority of profits, while the trend component contributes modest gains during sustained moves.</p>
</div>

<p>
  We also test a "dual" strategy that runs mean-reversion during MR regimes and trend-following during
  trending regimes. The trend-following component enters in the direction of the Kalman drift when the
  HMM is in State 1, with wider stops (SL = $5) to accommodate the higher volatility. The dual strategy
  produces a combined profit factor of 1.29, lower than the MR-only strategy (1.42), because the
  trend-following component is only marginally profitable (PF 1.08). Gold's trending regimes at the M1
  scale are too short-lived and noisy for simple trend-following to capture meaningful gains after
  transaction costs.
</p>

<h3>5.5 HMM Trend Decomposition</h3>

<div style="margin: 2rem 0;">
  <img src="/charts/kalman/hmm_trend_decompose.png" alt="HMM trend decomposition analysis" style="width: 100%; border-radius: 0.5rem; border: 1px solid #e5e7eb;" />
  <p class="figure-caption">Figure 8: Decomposition of gold returns by HMM regime. The top panel shows cumulative returns attributed to each regime. The bottom panel shows the rolling 60-bar return distribution within each state, confirming the separation of low-volatility (MR) and high-volatility (Trend) regimes.</p>
</div>

<p>
  Decomposing gold returns by HMM state reveals that the mean-reverting regime accounts for
  approximately 55&ndash;60% of total bars but contributes the majority of tradeable mean-reversion
  signals. The trending regime, while accounting for only 35&ndash;40% of bars, contributes
  disproportionately to large directional moves. This asymmetry explains why HMM-filtered
  mean-reversion strategies achieve better risk-adjusted returns: they avoid the minority of
  bars where mean-reversion is counterproductive.
</p>

<h3>5.6 Mean Absolute Error Analysis</h3>

<div style="margin: 2rem 0;">
  <img src="/charts/kalman/hmm_mae_analysis.png" alt="HMM prediction error analysis by regime" style="width: 100%; border-radius: 0.5rem; border: 1px solid #e5e7eb;" />
  <p class="figure-caption">Figure 9: Mean absolute error (MAE) of the Kalman drift forecast by HMM regime. The Kalman filter's predictive accuracy is significantly better during MR regimes (lower MAE) than during trending regimes, confirming that the filter's state-space model is better specified for range-bound markets.</p>
</div>

<p>
  The MAE analysis provides a diagnostic for the Kalman filter's accuracy across regimes. During
  mean-reverting regimes, the Kalman drift estimate tracks the realised drift with lower error,
  validating the model's assumption of slowly-varying drift plus noise. During trending regimes,
  the MAE increases substantially because the true drift is changing faster than the filter's
  low $Q$ parameter allows it to track. This mismatch between the filter's assumptions and the
  trending regime's dynamics is precisely why mean-reversion signals generated during trends are
  unreliable.
</p>

<h2>6. Discussion</h2>

<h3>6.1 Does HMM Filtering Improve the Kalman Strategy?</h3>

<p>
  The answer depends on the objective. For <strong>risk-adjusted returns</strong> (Sharpe ratio,
  Calmar ratio, profit factor per trade), the HMM unambiguously improves the strategy. The Sharpe
  ratio increases from 0.92 to 1.08 (+17%), the max drawdown decreases from $28.4 to $21.7
  (&minus;24%), and the average trade increases from $0.41 to $0.53 (+29%).
</p>

<p>
  For <strong>absolute returns</strong>, the HMM hurts: total P&L drops from $265 to $223
  (&minus;16%) because the filter removes 35% of trades, and even the removed trades had a
  slight positive expectancy. This is the classic precision-recall trade-off &mdash; higher
  precision (better per-trade quality) at the cost of lower recall (fewer total trades).
</p>

<p>
  For a capital-constrained trader who can only allocate a fixed amount to this strategy, the
  HMM-filtered version is strictly superior: it produces better returns per unit of risk and
  requires smaller maximum capital commitment (lower drawdown). For a trader who can scale
  position size freely and is evaluated on total P&L, the unfiltered version generates more
  profit despite its lower quality.
</p>

<h3>6.2 Regime Stability Issues</h3>

<p>
  The HMM's effectiveness is limited by three stability concerns:
</p>

<ul>
  <li><strong>Transition boundary errors:</strong> The HMM is least reliable at regime transition
    points, exactly when correct classification matters most. Trades near transitions (within 10 bars)
    show no edge regardless of the HMM's classification. A softer transition model (e.g., using
    posterior probabilities as position-sizing weights rather than hard 0/1 classification) could
    mitigate this issue.</li>
  <li><strong>Parameter instability:</strong> The HMM's emission and transition parameters shift
    as the training window slides forward. The emission means ($\\mu_k$) are relatively stable,
    but the emission variances ($\\sigma_k^2$) and transition probabilities ($A_{ij}$) can change
    substantially between training windows. This means the "mean-reverting" and "trending" regimes
    are not fixed statistical objects but evolving categories whose properties drift over time.</li>
  <li><strong>Label switching:</strong> HMMs are subject to label switching, where the assignment
    of State 0 and State 1 to "mean-reverting" and "trending" can swap between training windows.
    We mitigate this by always assigning the lower-volatility state as "mean-reverting," but
    edge cases exist where both states have similar volatility and the classification becomes
    ambiguous.</li>
</ul>

<h3>6.3 Comparison with Simple Alternatives</h3>

<p>
  A natural question is whether the Kalman filter and HMM machinery is justified by its performance
  relative to simpler alternatives. We compare the Kalman+HMM strategy against two baselines:
</p>

<ul>
  <li><strong>Simple MA crossover mean-reversion:</strong> Replace the Kalman-filtered price with a
    60-bar simple moving average. Enter short when price is above MA by more than 1 ATR, long when
    below. Same SL/TP grid. This produces a profit factor of 1.18 (vs. 1.34 for Kalman-only and
    1.42 for Kalman+HMM), confirming that the Kalman filter's adaptive smoothing adds value over
    fixed-window averaging.</li>
  <li><strong>Volatility regime filter (rolling ATR):</strong> Replace the HMM with a simple
    high/low volatility classification based on whether the 60-bar ATR is above or below its
    240-bar median. Only trade when ATR is below median (low vol = proxy for mean-reverting).
    This produces a profit factor of 1.31 (vs. 1.42 for Kalman+HMM), suggesting that the HMM
    captures regime information beyond what a simple volatility threshold provides, but the
    marginal improvement is modest.</li>
</ul>

<h3>6.4 Limitations</h3>

<p>
  Several limitations constrain the generalisability of these results:
</p>

<ul>
  <li><strong>Single instrument:</strong> All results are for XAUUSD only. Gold has specific
    microstructural properties (24-hour trading, session-dependent volatility, safe-haven flows)
    that may not generalise to other instruments.</li>
  <li><strong>Fixed Kalman parameters:</strong> The process noise $Q$ and observation noise $R$
    are fixed throughout. Adaptive estimation of these parameters (e.g., via the EM algorithm
    or innovation-based methods) could improve the filter's tracking during regime transitions.</li>
  <li><strong>2-state HMM:</strong> We use only two states. A 3-state model (mean-reverting,
    trending-up, trending-down) could provide finer regime classification, though at the cost
    of increased parameter count and potential overfitting.</li>
  <li><strong>No walk-forward HMM retraining:</strong> The HMM is trained on the full dataset
    for simplicity. A proper walk-forward implementation would retrain the HMM on each rolling
    window, which would reduce the effective sample size for HMM estimation and likely degrade
    performance.</li>
</ul>

<h2>7. Conclusion</h2>

<p>
  The Kalman drift filter provides a principled, adaptive framework for estimating the latent trend
  in gold M1 returns. With heavy smoothing ($Q/R = 10^{-3}$), the filter extracts the slow-moving
  drift component while rejecting microstructure noise. Deviations from the filtered price generate
  mean-reversion signals that produce a profit factor of 1.34 and an annualised Sharpe ratio of 0.92
  across 647 trades, after $0.20 spread cost.
</p>

<p>
  Adding a 2-state HMM regime overlay improves per-trade quality metrics: the profit factor increases
  to 1.42, the Sharpe ratio to 1.08, and the max drawdown decreases by 24%. However, the HMM filter
  suppresses 35% of trades, reducing total cumulative P&L by 16%. The HMM is most valuable for
  identifying <em>stable</em> mean-reverting periods (far from regime transitions), where trade
  quality is highest (58.2% win rate, PF 1.61), and for avoiding the transition boundary zone
  where neither regime classification is reliable.
</p>

<p>
  The practical implication is that the HMM is better suited as a position-sizing tool than a
  binary filter. Rather than suppressing all trades during trending regimes, a softer approach
  would scale position size by the HMM posterior probability of the mean-reverting state: full
  size when the posterior exceeds 0.9, half size between 0.5 and 0.9, and no trade below 0.5.
  This would preserve more of the cumulative P&L while still benefiting from the HMM's regime
  information.
</p>

<blockquote>
  The Kalman filter extracts the slow-moving drift in gold returns, and deviations from the filtered
  price offer a genuine mean-reversion signal. The HMM improves signal precision at the cost of
  signal volume, a trade-off that favours risk-adjusted over absolute returns. The combination is most
  powerful not as a binary on/off switch but as a continuous position-sizing overlay: trade aggressively
  in stable MR regimes, conservatively near transitions, and not at all during clear trending episodes.
  For production deployment, the primary risk is HMM parameter instability across training windows,
  which requires ongoing monitoring of regime classification consistency.
</blockquote>
`;
